/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppointmentImport } from './routes/appointment'
import { Route as AppointmentIndexImport } from './routes/appointment.index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AppointmentRoute = AppointmentImport.update({
  path: '/appointment',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AppointmentIndexRoute = AppointmentIndexImport.update({
  path: '/',
  getParentRoute: () => AppointmentRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/appointment': {
      preLoaderRoute: typeof AppointmentImport
      parentRoute: typeof rootRoute
    }
    '/appointment/': {
      preLoaderRoute: typeof AppointmentIndexImport
      parentRoute: typeof AppointmentImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AppointmentRoute.addChildren([AppointmentIndexRoute]),
])

/* prettier-ignore-end */
